<a href="https://colab.research.google.com/github/Pavancode-py/My-work-of-practice/blob/main/Inprogress.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CREATING A LOGISTIC REGRESSION TO PREDICT ABSENTISM


In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

LOAD THE PREPROCESSED DATA

In [2]:
data_preprocessed = pd.read_csv("/content/Absenteeism_preprocessed.csv")
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

CREATE THE TARGETS

In [3]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] >
                   data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [4]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets

In [6]:
data_preprocessed.head()

Reason1  Reason2  Reason3  Reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                1   
1        0        0        0        0            7                1   
2        0        0        0        1            7                2   
3        1        0        0        0            7                3   
4        0        0        0        1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

A comment on Targets

In [7]:
targets.sum()/targets.shape[0]

np.float64(0.45571428571428574)

In [8]:
data_with_targets =  data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)
data_with_targets

Reason1  Reason2  Reason3  Reason4  Month Value  Day of the Week  \
0          0        0        0        1            7                1   
1          0        0        0        0            7                1   
2          0        0        0        1            7                2   
3          1        0        0        0            7                3   
4          0        0        0        1            7                3   
..       ...      ...      ...      ...          ...              ...   
695        1        0        0        0            5                2   
696        1        0        0        0            5                2   
697        1        0        0        0            5                3   
698        0        0        0        1            5                3   
699        0        0        0        1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  Excessive Absenteeism  
0                 30          0         2     1                      1  
1                 31          0         1     0                      0  
2                 31          0         0     0                      0  
3                 24          0         2     0                      1  
4                 30          0         2     1                      0  
..               ...        ...       ...   ...                    ...  
695               22          1         2     0                      1  
696               24          0         1     2                      0  
697               25          1         0     0                      1  
698               25          1         0     0                      0  
699               25          0         1     1                      0  

[700 rows x 15 columns]

SELECT THE INPUTS FOR REGRESSION

In [9]:
data_with_targets.shape

(700, 15)

In [10]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

STANDARDIZE THE DATA

In [11]:
absentism_scaler = StandardScaler()

In [12]:
absentism_scaler.fit(unscaled_inputs)

StandardScaler()

In [13]:
scaled_inputs = absentism_scaler.transform(unscaled_inputs)

In [14]:
scaled_inputs.shape

(700, 14)

In [15]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [16]:
# train_test_split(scaled_inputs,targets)

In [17]:
X_train,X_temp,y_train,y_temp = train_test_split(scaled_inputs,targets,train_size=0.8,random_state=0)

In [18]:
print(X_train.shape, y_train.shape)

(560, 14) (560,)


In [19]:
print(X_temp.shape, y_temp.shape)

(140, 14) (140,)


LOGISTIC REGRESSION

In [20]:
reg = LogisticRegression()

In [21]:
reg.fit(X_train,y_train)

LogisticRegression()

In [22]:
reg.score(X_train,y_train)

0.775

FINDING THE COEFFCIENTS AND INTERCEPT

In [23]:
reg.coef_

array([[ 2.0096967 ,  0.25874312,  1.56085716,  1.3289186 ,  0.08210274,
        -0.1551629 ,  0.72542849,  0.03179246, -0.18720274,  0.05225617,
         0.26080165,  0.05602753,  0.52039495, -0.37128392]])

In [24]:
reg.intercept_

array([-0.22178064])